### ISSUE TITLE
Error send

### ISSUE THREAD

**Issue by Artem-1024** [NeuraiProject/electrum-neurai#7]
When i try to send coins to another wallet, i get an error. Try version 2.0 and 2.1. 
Now I re-install my OS Windows 10. Install Electrum Neurai 0.2.1 but have the same error:

Traceback
Traceback (most recent call last):
  File "electrum\gui\qt\send_tab.py", line 612, in do_pay_or_get_invoice
  File "electrum\gui\qt\send_tab.py", line 711, in do_pay_invoice
  File "electrum\gui\qt\send_tab.py", line 389, in pay_onchain_dialog
  File "electrum\gui\qt\send_tab.py", line 583, in save_pending_invoice
  File "electrum\wallet.py", line 1213, in save_invoice
  File "electrum\wallet.py", line 424, in save_db
  File "electrum\json_db.py", line 274, in write
  File "electrum\util.py", line 480, in do_profile
  File "electrum\json_db.py", line 283, in _write
  File "electrum\json_db.py", line 49, in wrapper
  File "electrum\json_db.py", line 234, in dump
  File "json\__init__.py", line 238, in dumps
  File "json\encoder.py", line 201, in encode
MemoryError
 
Additional information
Electrum version: 0.2.1 
Python version: 3.10.11 (tags/v3.10.11:7d4cc5a, Apr 5 2023, 00:20:04) [MSC v.1929 32 bit (Intel)] 
Operating system: Windows-10-10.0.17134-SP0 
Wallet type: standard 
Locale: en_US 

Have any suggestions?

![Screenshot_1](https://github.com/NeuraiProject/electrum-neurai/assets/139905139/5ba99a5d-1a28-4413-97d6-f10c6f4d133f)

**Comment by NeuraiProject** [comment]
Although you don't mention it, the problem may be having a very large history and the program memory cannot store it.

The best thing to do if this is the problem is to send everything from Neurai-QT to a new address to avoid all the previous transaction history.

Electrum was not really intended to handle very large transaction histories and it works badly when there are such wallets.
